### PR TITLE
Reduce memory allocations in desktop implementation

### PR DESCRIPTION
**Pull request by tomcashman**
We noticed a lot of allocations due to new ControllerQuerier instances and boxing from Float/Boolean to float/boolean.

### CODE REVIEW

**Comment by MrStahlfelge** [comment]
You are right about that. Code changes look good to me, I will test the PR next week and merge it afterwards.

Thanks for your PR.

**Comment by MrStahlfelge** [comment]
There is some more unnecessary boxing in CompositeControllerListener.

**Comment by MrStahlfelge** [comment]
Thanks for your contribution. Feel free to change the CompositeControllerListener if you think it should be changed.

By the way, would be great to see you on the Discord server. Link to join is on the main readme.

**Comment by tomcashman** [comment]
Thanks. Made a PR for CompositeControllerListener :) Do you think a new release will be soon?

I'm already on the Discord, I don't talk much XD

**Comment by MrStahlfelge** [comment]
Please PN me on discord, I didn't find your user handle.

Do you need a new version soon? I wanted to add a platform-independant way to retrieve the default button/axis constants to `AdvancedController` and am waiting for 1.9.10 to be released before releasing a new version. I aim to make a release at least every two months for all of my libs.

**Pull request merged**
